// flow-typed signature: 5a1f1086023f2476a8274b9e45531c92
// flow-typed version: <<STUB>>/@types/dotenv_v^8.2.0/flow_v0.165.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/dotenv' {
  declare module.exports: any;
}
